#############################################################################
# Makefile for building: Tetris.app/Contents/MacOS/Tetris
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  Tetris.pro
# Template: app
# Command: /Applications/Qt/5.4/clang_64/bin/qmake -o Makefile Tetris.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.9 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.9 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -I. -I/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Qt/5.4/clang_64/mkspecs/macx-clang -F/Applications/Qt/5.4/clang_64/lib
QMAKE         = /Applications/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Tetris1.0.0
DISTDIR = /Users/lxl/qt??/Tetris/.tmp/Tetris1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.9 -Wl,-rpath,/Applications/Qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/Qt/5.4/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qboarddata.cpp \
		qpiece.cpp \
		qshowboard.cpp moc_mainwindow.cpp \
		moc_qboarddata.cpp \
		moc_qshowboard.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qboarddata.o \
		qpiece.o \
		qshowboard.o \
		moc_mainwindow.o \
		moc_qboarddata.o \
		moc_qshowboard.o
DIST          = /Applications/Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		../../.qmake.stash \
		/Applications/Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/lex.prf \
		Tetris.pro mainwindow.h \
		qboarddata.h \
		qpiece.h \
		qshowboard.h main.cpp \
		mainwindow.cpp \
		qboarddata.cpp \
		qpiece.cpp \
		qshowboard.cpp
QMAKE_TARGET  = Tetris
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Tetris.app/Contents/MacOS/Tetris

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.9 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h ui_qboarddata.h ui_qshowboard.h $(OBJECTS)  
	@test -d Tetris.app/Contents/MacOS/ || mkdir -p Tetris.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Tetris.pro /Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		../../.qmake.stash \
		/Applications/Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.4/clang_64/mkspecs/features/lex.prf \
		Tetris.pro \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Tetris.pro
/Applications/Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt/5.4/clang_64/mkspecs/qdevice.pri:
/Applications/Qt/5.4/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/unix.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/mac.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/macx.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/clang.conf:
/Applications/Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt/5.4/clang_64/mkspecs/qconfig.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
../../.qmake.stash:
/Applications/Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/qt.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/resources.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/moc.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/uic.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt/5.4/clang_64/mkspecs/features/lex.prf:
Tetris.pro:
/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Tetris.pro

qmake_all: FORCE

Tetris.app/Contents/PkgInfo: 
	@test -d Tetris.app/Contents || mkdir -p Tetris.app/Contents
	@$(DEL_FILE) Tetris.app/Contents/PkgInfo
	@echo "APPL????" >Tetris.app/Contents/PkgInfo
Tetris.app/Contents/Resources/empty.lproj: 
	@test -d Tetris.app/Contents/Resources || mkdir -p Tetris.app/Contents/Resources
	@touch Tetris.app/Contents/Resources/empty.lproj
	
Tetris.app/Contents/Info.plist: 
	@test -d Tetris.app/Contents || mkdir -p Tetris.app/Contents
	@$(DEL_FILE) Tetris.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,YuQing.Tetris,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Tetris,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >Tetris.app/Contents/Info.plist

all: Makefile \
		Tetris.app/Contents/PkgInfo \
		Tetris.app/Contents/Resources/empty.lproj \
		Tetris.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h qboarddata.h qpiece.h qshowboard.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp qboarddata.cpp qpiece.cpp qshowboard.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui qboarddata.ui qshowboard.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Tetris.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_qboarddata.cpp moc_qshowboard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qboarddata.cpp moc_qshowboard.cpp
moc_mainwindow.cpp: /Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		qboarddata.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFrame \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		qpiece.h \
		qshowboard.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLCDNumber \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		mainwindow.h
	/Applications/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Applications/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/lxl/qt成品/Tetris -I/Users/lxl/qt成品/Tetris -I/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Headers -I. -F/Applications/Qt/5.4/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_qboarddata.cpp: /Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFrame \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		qpiece.h \
		qboarddata.h
	/Applications/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Applications/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/lxl/qt成品/Tetris -I/Users/lxl/qt成品/Tetris -I/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Headers -I. -F/Applications/Qt/5.4/clang_64/lib qboarddata.h -o moc_qboarddata.cpp

moc_qshowboard.cpp: /Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		qpiece.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		qshowboard.h
	/Applications/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Applications/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/lxl/qt成品/Tetris -I/Users/lxl/qt成品/Tetris -I/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Headers -I. -F/Applications/Qt/5.4/clang_64/lib qshowboard.h -o moc_qshowboard.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_qboarddata.h ui_qshowboard.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_qboarddata.h ui_qshowboard.h
ui_mainwindow.h: mainwindow.ui
	/Applications/Qt/5.4/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_qboarddata.h: qboarddata.ui
	/Applications/Qt/5.4/clang_64/bin/uic qboarddata.ui -o ui_qboarddata.h

ui_qshowboard.h: qshowboard.ui
	/Applications/Qt/5.4/clang_64/bin/uic qshowboard.ui -o ui_qshowboard.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		qboarddata.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFrame \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		qpiece.h \
		qshowboard.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLCDNumber \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		qboarddata.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFrame \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		qpiece.h \
		qshowboard.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLCDNumber \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		ui_mainwindow.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/complexwidgets.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/itemviews.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblemenu.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidgets.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/rangecontrols.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/simplewidgets.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qboarddata.o: qboarddata.cpp qboarddata.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFrame \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		qpiece.h \
		ui_qboarddata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qboarddata.o qboarddata.cpp

qpiece.o: qpiece.cpp qpiece.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/complexwidgets.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/itemviews.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblemenu.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidgets.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/rangecontrols.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/simplewidgets.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qpiece.o qpiece.cpp

qshowboard.o: qshowboard.cpp qshowboard.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		qpiece.h \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		ui_qshowboard.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/complexwidgets.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/itemviews.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblemenu.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidgets.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/rangecontrols.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/simplewidgets.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qshowboard.o qshowboard.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qboarddata.o: moc_qboarddata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qboarddata.o moc_qboarddata.cpp

moc_qshowboard.o: moc_qshowboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qshowboard.o moc_qshowboard.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

